name: Bad Practices CI/CD

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: Dependencies
        run: pip install -r requirements.txt

      - name: API and others keys
        env:
          API_KEY: "key ****"
        run: echo "API Key - $API_KEY"

      - name: Tests and deploy
        run: |
          pytest || echo "Error test"
          echo "Deploying"
          ./deploy.sh
