version: '3.8'

services:

  app1:
    image: app:1.3
    container_name: app_1_new
    networks:
      - app1_network
    environment:
      - API_KEY=${API_KEY}
    deploy:
      resources:
        limits:
          memory: 32M

  app2:
    build:
      context: ./app_system
      dockerfile: Dockerfile
    container_name: app_2_new
    networks:
      - app2_network
    environment:
      - API_KEY=${API_KEY}
    deploy:
      resources:
        limits:
          memory: 64M

networks:
  app1_network:
    driver: bridge
  app2_network:
    driver: bridge
